### ISSUE TITLE
re indexin logic not working properly 

### ISSUE THREAD

**Issue by 19031987** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#39] opened 2018-02-14 19:52 UTC
when i am trying to click on the re indexing link in admin which was created after using command yo jhipster-elasticsearch-reindexer is not working, the navigation to page is not working code inside it is there 
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.caf.valididty"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "ca",
    "packageName": "com.caf.valididty",
    "packageFolder": "com/caf/valididty",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "e6209413147382cdf9befb930e1ad7e8debc054a",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }
}

I have updated jhipster-elasticsearch-reindexer ,  could you please suggest me what can be done.

**Comment by geraldhumphries** [comment] 2018-02-14 20:30
Can you provide more info? Is there an error in the console? What is the actual behaviour?

**Comment by geraldhumphries** [comment] 2018-03-25 20:07
I am closing this issue because I haven't been able to reproduce this, and no more info was provided.

If this is still a problem you should provide the info I requested above and reopen this issue.

**Closed by geraldhumphries** 2018-03-25 20:07 UTC
