### ISSUE TITLE
IllegalArgumentException: No id property found for class

### ISSUE THREAD

**Issue by jdanosborne** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#20] opened 2017-02-01 20:48 UTC
Having got a basic jhipster app working with some generated entities and your reindexer I'm trying to target a pre-existing mysql schema where the pk is not an auto-generated id. 

I've changed my domain class Gn_client from...

@Id
@GeneratedValue(strategy = GenerationType.AUTO)
private Long id;

to...

@Id
@Size(max = 5)
@Column(name = "instanceId", length = 5)
private String instanceId;

and to reflect the change of type of the id I've changed the generated ElasticsearchIndexService.reindexAll() replacing...

reindexForClass(Gn_client.class, gn_clientRepository, gn_clientSearchRepository) with ...
reindexForStringClass(Gn_client.class, gn_clientRepository, gn_clientSearchRepository)

within which I use <T, String> rather than <T, Long>

However I get a runtime error at startup...

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchIndexService': Unsatisfied dependency expressed through field 'gn_clientSearchRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gn_clientSearchRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No id property found for class com.dan.jh.domain.Gn_client!

The Gn_clientSearchRepository has Long changed to String...

public interface Gn_clientSearchRepository extends ElasticsearchRepository<Gn_client, String>

Any pointers as to why it still seems to be looking for an "id property" would be much appreciated.

Dan

**Comment by geraldhumphries** [comment] 2017-02-07 19:56
Does your app still work without the Elasticsearch index service/repository with a string id?

**Comment by jdanosborne** [comment] 2017-02-07 20:44
I'm not sure yet - this error stops the app from getting going. I'll try
removing the index service and see.

Dan

**Comment by jdanosborne** [comment] 2017-02-07 21:47
No, with the ElasticsearchIndexService removed it gives the same error ...

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gn_clientSearchRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No id property found for class com.dan.jh.domain.Gn_client!

I see someone else had a similar problem http://stackoverflow.com/questions/33495742/how-to-rename-id-field-in-an-entity-using-with-elasticsearch and looks to have not found a solution.

Maybe it is a jhipster restriction to have SearchRepositories with numeric id fields?

**Comment by geraldhumphries** [comment] 2017-02-07 22:37
I don't think it's a JHipster or ES reindexer specific issue, but a Spring Data Elasticsearch issue. I tried the same changes for one of my entities and had the same issue. When I DID NOT remove the id field (but annotated the string with `@Id`), I was able to boot successfully.

Instead of creating a separate reindex method for the String id classes, you can change the signature of the existing one to this:

```
    private <T, ID extends Serializable> void reindexForClass(Class<T> entityClass, JpaRepository<T, ID> jpaRepository,
                                                              ElasticsearchRepository<T, ID> elasticsearchRepository) {
```

That should work properly once we figure out the String id class.

I will debug the issue and let you know how it turns out. I am leaning towards it being a but in Spring Data Elasticsearch. I am closing this issue because this repo is unrelated but I will continue to help.

**Closed by geraldhumphries** 2017-02-07 22:37 UTC

**Comment by jdanosborne** [comment] 2017-02-08 07:27
Ah, that sounds promising - and thanks for helping.

I'll try keeping an id field and see if that provides a workaround.

Dan

**Comment by jdanosborne** [comment] 2017-02-08 07:45
Adding a private long id field (unannotated) to the entity gets me through the boot process OK but when trying to create a new record it says...

Exception in com.dsn.jh.web.rest.Gn_clientResource.createGn_client() with cause = 'org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned beforeQuery calling save(): com.dan.jh.domain.Gn_client' and exception = 'ids for this class must be manually assigned beforeQuery calling save(): com.pharos.jh.domain.Gn_client; nested exception is org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned beforeQuery calling save(): com.dan.jh.domain.Gn_client'

So is it insisting on having a non-null id column still in my database table do you think?

Dan

**Comment by geraldhumphries** [comment] 2017-02-08 15:37
Are you assigning a value to `instanceId` before saving it?

**Comment by jdanosborne** [comment] 2017-02-08 16:08
Not explicitly but it is an existing required field in the entity and on the UI etc so it will have a value before trying to save.

**Comment by geraldhumphries** [comment] 2017-02-22 19:32
Any luck so far? I will add non-Long ID support like I mentioned above. Let me know if you've figured it out yet.

When I was investigating myself, I noticed that Spring Data Elasticsearch initially picks up the String PK field properly. However when it comes time to validate that every entity has a PK, it's null. Still haven't discovered the cause.

**Comment by jdanosborne** [comment] 2017-02-22 20:57
No I'm afraid not. The post to create a new record is passed the instanceId...
http://localhost:8080/api/gn-clients?cacheBuster=1487792798991
{"instanceId":"xxx","name":"xxxxxxxx","xchangeUser":"user","xchangePSW":"pwd","id":null}

but by the time it gets to the web/rest/Gn_clientResource.createGn_client() method  Gn_client.instanceId is null...

    @PostMapping("/gn-clients")
    @Timed
    public ResponseEntity<Gn_client> createGn_client(@Valid @RequestBody Gn_client gn_client)

I've tried debugging it in STS but there is a lot of Spring voodoo that I can't make much sense of - If you have any pointers on how best to follow the processing flow through from the starting POST it would be much appreciated.
