### ISSUE TITLE
"Could not compose module" when batch-generating entities

### ISSUE THREAD

**Issue by jnuc093** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#32] opened 2017-09-10 07:40 UTC
➜  blog npm install -g generator-jhipster-elasticsearch-reindexer
/Users/qk/.nvm/versions/node/v7.7.4/lib
└─┬ generator-jhipster-elasticsearch-reindexer@1.0.1
  └─┬ generator-jhipster@4.7.0
    └─┬ yeoman-environment@2.0.2
      └─┬ inquirer@3.2.3
        └─┬ external-editor@2.0.4
          └── iconv-lite@0.4.19

➜  blog git:(master) jhipster import-jdl /Users/qk/myosgit/blog/src/main/resources/dsl/equipment-jdl.jh
Executing jhipster:import-jdl /Users/qk/myosgit/blog/src/main/resources/dsl/equipment-jdl.jh
The jdl is being parsed.
Writing entity JSON files.
Generating entities.

Found the .jhipster/MxpmsSearchEquipment.json configuration file, entity can be automatically generated!

The entity MxpmsSearchEquipment is being updated.

identical src/main/resources/config/liquibase/changelog/20170910070621_added_entity_MxpmsSearchEquipment.xml
identical src/main/java/com/sgcc/pms/domain/MxpmsSearchEquipment.java
identical src/main/java/com/sgcc/pms/repository/MxpmsSearchEquipmentRepository.java
identical src/main/java/com/sgcc/pms/web/rest/MxpmsSearchEquipmentResource.java
identical src/main/java/com/sgcc/pms/service/dto/MxpmsSearchEquipmentDTO.java
identical src/main/java/com/sgcc/pms/service/mapper/EntityMapper.java
identical src/main/java/com/sgcc/pms/service/mapper/MxpmsSearchEquipmentMapper.java
identical src/test/java/com/sgcc/pms/web/rest/MxpmsSearchEquipmentResourceIntTest.java
identical src/main/resources/config/liquibase/master.xml

Running post run module hooks

Could not compose module generator-jhipster-elasticsearch-reindexer.
Make sure you have installed the module with 'npm -g generator-jhipster-elasticsearch-reindexer'
Execution complete

the source code is [here](http://git.oschina.net/jnuc093/blog)

**Comment by jnuc093** [comment] 2017-09-10 08:20
➜  blog git:(master) ✗ ./mvnw
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Blog 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.5.6.RELEASE:run (default-cli) > test-compile @ blog >>>
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ blog ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ blog ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ blog ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (pre-unit-tests) @ blog ---
[INFO] argLine set to -javaagent:/Users/qk/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/qk/myosgit/blog/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ blog ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 54 source files to /Users/qk/myosgit/blog/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[6,1] 程序包com.sgcc.pms.repository.search不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[7,33] 程序包org.elasticsearch.indices不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[10,51] 程序包org.springframework.data.elasticsearch.core不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[11,57] 程序包org.springframework.data.elasticsearch.repository不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[28,19] 找不到符号
  符号:   类 MxpmsSearchEquipmentSearchRepository
  位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[30,19] 找不到符号
  符号:   类 ElasticsearchTemplate
  位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[34,9] 找不到符号
  符号:   类 MxpmsSearchEquipmentSearchRepository
  位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[35,9] 找不到符号
  符号:   类 ElasticsearchTemplate
  位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[52,63] 找不到符号
  符号:   类 ElasticsearchRepository
  位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[INFO] 9 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.357 s
[INFO] Finished at: 2017-09-10T16:20:33+08:00
[INFO] Final Memory: 53M/535M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project blog: Compilation failure: Compilation failure:
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[6,1] 程序包com.sgcc.pms.repository.search不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[7,33] 程序包org.elasticsearch.indices不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[10,51] 程序包org.springframework.data.elasticsearch.core不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[11,57] 程序包org.springframework.data.elasticsearch.repository不存在
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[28,19] 找不到符号
[ERROR]   符号:   类 MxpmsSearchEquipmentSearchRepository
[ERROR]   位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[30,19] 找不到符号
[ERROR]   符号:   类 ElasticsearchTemplate
[ERROR]   位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[34,9] 找不到符号
[ERROR]   符号:   类 MxpmsSearchEquipmentSearchRepository
[ERROR]   位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[35,9] 找不到符号
[ERROR]   符号:   类 ElasticsearchTemplate
[ERROR]   位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] /Users/qk/myosgit/blog/src/main/java/com/sgcc/pms/service/ElasticsearchIndexService.java:[52,63] 找不到符号
[ERROR]   符号:   类 ElasticsearchRepository
[ERROR]   位置: 类 com.sgcc.pms.service.ElasticsearchIndexService
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by jnuc093** [comment] 2017-09-10 08:24
the package com.sgcc.pms.repository.search  does't generate successfully. how can i resolve it

**Comment by jnuc093** [comment] 2017-09-11 01:21
Your project's .yo-rc.json does not use elasticsearch: "searchEngine": false,.

Replace it with "searchEngine": "elasticsearch", and re-generate it with jhipster --with-entities then re-install indexer module.

Beside this, we recommend using an LTS version of Node (currently 6.x), you're using 7.7.4.

EDIT:

Your project uses yarn, It's usually a bad idea to mix with npm, so instead of using:

npm install -g generator-jhipster-elasticsearch-reindexer
You should rather use:

yarn global add generator-jhipster-elasticsearch-reindexer

https://stackoverflow.com/questions/46138799/jhipster-elastic-search-reindexer-generate-fail/46139477?noredirect=1#comment79246671_46139477

**Comment by geraldhumphries** [comment] 2017-09-12 16:10
@gmarziou What error were you able to reproduce?

**Comment by jakobhostnik** [comment] 2018-03-12 08:29
Have same issue.
![image](https://user-images.githubusercontent.com/16599456/37272711-ced00376-25d7-11e8-8661-89ee147ea01d.png)

**Comment by geraldhumphries** [comment] 2018-03-12 16:30
@jakobhostnik What version of JHipster/Yeoman are you running? What happens when you run the generator manually? This might have something to do with the post run module hooks.

**Comment by jakobhostnik** [comment] 2018-03-12 18:53
I manually updated jhipster project to newest version. But I have not touched frontend. And I had problems so I deleted whole frontend and generated it again with jhipster --skip-server  --with-entities.
Then I installed plugin again. In every order of operations. Still same error

**Comment by geraldhumphries** [comment] 2018-03-12 19:54
Have you tried running elasticsearch-reindexer manually? Do you still get the same error?

**Comment by jakobhostnik** [comment] 2018-03-12 20:18
I did. Same error. I am trying again with removing reindexer completely. And then installing

**Comment by jakobhostnik** [comment] 2018-03-12 20:48
Over and over again this error.
![image](https://user-images.githubusercontent.com/16599456/37308702-1ee4079c-263f-11e8-9dc7-609dbaf8b139.png)

**Comment by jakobhostnik** [comment] 2018-03-12 20:53
![image](https://user-images.githubusercontent.com/16599456/37308906-a218e358-263f-11e8-878d-ee5520a40848.png)
![image](https://user-images.githubusercontent.com/16599456/37308933-b27b73dc-263f-11e8-952c-6299fd728bd5.png)

**Comment by geraldhumphries** [comment] 2018-03-12 20:54
Okay, the second error looks like #43. Try the suggested code in that issue.

The first error looks like it was resolved, when did it stop happening?

**Comment by jakobhostnik** [comment] 2018-03-12 20:56
In some weird cases it is still shown. But yes we can say it is resolved. Thank you very much. 
And by the way. You are the best. You and whole jhipster community.

**Comment by geraldhumphries** [comment] 2018-03-12 21:05
There is still an issue here with module composition. I will do some testing when I get some time.

**Comment by geraldhumphries** [comment] 2018-03-25 19:39
I was able to reproduce.

This happens with the following steps:

1. Generate an application using `yo jhipster`
2. Generate an entity using `yo jhipster:entity`
3. Run the elasticsearch-reindexer generator. This will add a post entity generation hook so it gets rerun.
4. Regenerate the frontend using `jhipster --skip-server --with-entities`. Replace all files.

The `--with-entities` option will regenerate entities and cause the hook to execute. I don't know why it's failing at this point, however. This is looking more like a bug with JHipster's post-entity module hook system.

Another way to reproduce:

1. Generate an application using `yo jhipster`
2. Generate an entity using `yo jhipster:entity`
3. Run the elasticsearch-reindexer generator. This will add a post entity generation hook so it gets rerun.
4. Batch-regenerate entities with `for f in ``ls .jhipster``; do jhipster entity ${f%.*} --force ; done`

The hook will work when generating an entity manually.

**Comment by geraldhumphries** [comment] 2018-03-27 14:40
I am closing this because it is looking like a JHipster bug related to local JHipster/global modules. Quick fix is to run JHipster globally by removing the `generator-jhipster` folder in `node_modules` or installing this (and all other) modules locally.

**Closed by geraldhumphries** 2018-03-27 14:40 UTC
